import os
from dotenv import load_dotenv
from langchain_groq import ChatGroq

load_dotenv()

def generate_investment_report(raw_agent_output: str, company: str) -> str:
    """
    Takes synthesized agent observations and formats them into
    a structured Markdown investment report.
    """
    llm = ChatGroq(
        model="llama-3.1-8b-instant",
        temperature=0.2,
        groq_api_key=os.getenv("GROQ_API_KEY")
    )

    prompt = f"""
Based on the following research findings about {company}, produce a professional 
investment research report in Markdown format. Be specific with numbers and data.

Research Findings:
{raw_agent_output}

Format EXACTLY as follows:

# 📊 Investment Research Report: {company}

## 1. Executive Summary
[3-4 sentences: overall assessment, key strengths, and buy/hold/sell stance]

## 2. Financial Health Analysis
[Revenue, margins, debt ratios, free cash flow — use specific numbers]

## 3. Earnings & Growth Analysis
[Recent earnings performance, YoY growth, forward guidance if available]

## 4. Price Trend Analysis
[6-month price movement, MA signals, momentum assessment]

## 5. Risk Assessment
[Risk score with label, top 3-5 risk factors ranked by severity]

## 6. News & Market Sentiment
[Key recent developments, analyst sentiment, any major catalysts]

## 7. Investment Verdict
**Recommendation:** [BUY / HOLD / SELL]  
**Time Horizon:** [Short / Medium / Long term]  
**Key Catalysts to Watch:** [2-3 bullet points]

---
*Report generated by Financial Research Agent | Sources: SEC Filings, Yahoo Finance, News*
"""
    response = llm.invoke(prompt)
    return response.content